#+TITLE: Title
#+AUTHOR: Author
#+EMAIL: haoran.mc@outlook.com
#+DATE: Date
#+STARTUP: showeverything
#+OPTIONS: toc:t ^:{} _:{}

Abstract.

* Heading 1
** Heading 2
*** Heading 3
**** Heading 4
***** Heading 5

*** Text
First Paragraph.

Body Text. Body Text Char.

| compare | elisp                     |
|---------+---------------------------|
| number  | (= 1 1)                   |
| string  | (equal "abc" "abc")       |
| array   | (equal [1 2 3] [1 2 3])   |
| list    | (equal '(a b c) '(a b c)) |
| object  | (eq 'a 'a)                |

* List
** Unordered List:
- *blod*
- /italic/
- +strick through+
- _underline_
- =verbatim=
- ~code~
- [[https://github.com/haoran-mc/.emacs.d][Hyperlink with description.]]

# \(H_{2}O\)
# \(E=mc^2\)


** Unordered List:
1. Chinese Font: 宋体
2. English Font: Courier


** DefinitionTerm:
- car :: the first S-expression.
  #+begin_quote
  The primitive /car/ is defined only for non-empty lists.
  #+end_quote

- cdr :: the list without the car part.
  #+begin_quote
  The primitive /cdr/ is defined only for non-empty lists. The /cdr/ of any non-empty list is always another list.
  #+end_quote

- cons :: adds any S-expression to the front of a list.
  #+begin_quote
  The primitive /cons/ takes two arguments. The second argument to /cons/ must be a list. The result is a list.
  #+end_quote

* Footnotes
Tom is a boy[fn:name].

Jim is a boy[fn:: This is the inline definition of this footnote] too.

Lily is a girl[fn:lily: a definition].

* TODO [#A] todo
The Org homepage[fn:1] now looks a lot better than it used to.

Any title becomes a TODO when it starts with ~TODO~.

You can indicate @emph[order] workflow status for the use of the "TODO" keyword:.

#+begin_src emacs-lisp
  (setq org-todo-keywords
        '((sequence "TODO" "FEEDBACK" "VERIFY" "|" "DONE" "DELEGATED")))
#+end_src

If you want to provide a pending status for a separate org file and add a key sequence to it, you can use the following configuration:

#+begin_example
  ,#+TODO: TODO(t) | DONE(d)
  ,#+TODO: REPORT(r) BUG(b) KNOWNCAUSE(k) | FIXED(f)
  ,#+TODO: | CANCELED(c)
#+end_example

When you use Org mode a lot, you may have a large number of to-do entries, and this is when you can set priority tags for them:

#+begin_example
  ,*** TODO [#A] Learn Elisp
#+end_example

There are three priority modes, A-C. If no priority is specified, the 'B' level is the default.

* COMMENT Footnotes
[fn:1] The link is: http://orgmode.org
[fn:name] Tom is a boy.
